--- 
title: "Postgraduate Research Methods and Analysis"
author: "Christopher J. Wilson"
date: '`r Sys.Date()`'
output:
  bookdown::html_book:
    theme: united
description: This is a handbook for postgraduate research methods courses in the psychology department at Teesside University.
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
css: style.css
---

# Overview

## Aims of the module

The module aims to introduce and develop core and advanced principles of quantitative psychological research design and statistical analysis. Specifically, it will begin with the foundations of designing and conducting empirical research projects and progress to explore a range of statistical analysis techniques and software suited to dealing with different kinds of data. The overall aim is to give students the confidence to develop appropriate research questions, generate testable hypotheses, design rigorous projects, collect data and select appropriate statistical procedures that lead to defensible scientific conclusions.   


## Learning Outcomes
On successful completion of this module, students will be able to:  

**Personal & Transferable Skills**

1. Display advanced competency in the numeric, statistical and analytical skills required for psychological research projects.

2. Demonstrate advanced knowledge and skills in research design.

3. Demonstrate effective ability to conduct and interpret statistical analyses using SPSS.

**Research Knowledge & Cognitive Skills**

4. Interpret and evaluate quantitative methods in psychology. 
Professional Skills

5. Demonstrate an in-depth knowledge and understanding of research design and applied statistical techniques relevant to a specialist area of psychology.   


## Indicative module content

**This module includes (but is not limited to):**

- Experimental, quasi-experimental and non-experimental research designs    
- Research Philosophy
- Ethics 
- Probability and Hypothesis Testing
- Power
- Moderation and Mediation
- Using R for data analysis
- Correlation and Regression
- ANOVA and Factorial ANOVA
- Reliability, Validity and Psychometrics


## Assessment

### Assessment details

**ECA (100% of the overall mark):** Produce a 3,000 word research report based on data gathered from a battery of psychological assessments to facilitate either a non-experimental or experimental design, including: a literature review, a testable research hypothesis, replicable methodology, appropriate results analysis, discussion of the findings and appropriate limitations and future work. *Learning outcomes: 1, 2, 3, 4 and 5.*

**Formative assessment:**
Formative assessment and feed forward are embedded within the module from an early stage. Verbal feed forward is provided during inquiry and practice based learning activities and assessment preparation sessions.

### Specific marking criteria for research report (in addition to generic assessment criteria): 

- Students should produce a detailed and evidence based rationale leading to a testable hypothesis.
- A methodology detailed enough for successful replication should be provided (including information on design, participants).
- Data should be analysed correctly via an appropriate method with evidence of correct interpretation and assumption checking.
- A discussion of the findings which relates results to theory should be presented.
Appropriate threats to validity should be evaluated and discussed as limitations and implications for future work.





```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')


library(knitr)
library(tidyverse)
library(car)

participant <- 1:20
happiness <- rnorm(20, mean = 10, sd = 1.4)
intervention <- factor(sample(c(1,2), 20, replace = T))

happinessSample <- as.data.frame(cbind(participant,intervention, happiness))

```



